language: java

script: mvn clean verify 
script: mvn package

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
    - master

install: /bin/true


